# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_pb2 as grpc__pb2


class GRPCServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetServerTime = channel.unary_unary(
        '/GRPCService/GetServerTime',
        request_serializer=grpc__pb2.Null.SerializeToString,
        response_deserializer=grpc__pb2.Timestamp.FromString,
        )


class GRPCServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetServerTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GRPCServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetServerTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetServerTime,
          request_deserializer=grpc__pb2.Null.FromString,
          response_serializer=grpc__pb2.Timestamp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GRPCService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
